name: install-and-build
on: [push, pull_request]

jobs:
  install-and-build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [ '12', '14' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run generate

  update-lockfile-and-build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [ '12', '14' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: rm package-lock.json
      - run: npm install
      - run: npm run generate
